# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\workspace\Nuclear_science_301\SynologyDrive\moun_PreDeal\LUMIS_CloudeServer_slaver\LUMIS_CloudeServer_slaver\UI\PlotUI_dailog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(767, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.spinBox_board_2 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_board_2.setObjectName("spinBox_board_2")
        self.horizontalLayout_4.addWidget(self.spinBox_board_2)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.spinBox_channel_2 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_channel_2.setMaximum(36)
        self.spinBox_channel_2.setObjectName("spinBox_channel_2")
        self.horizontalLayout_4.addWidget(self.spinBox_channel_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.spinBox_baseLine_2 = QtWidgets.QSpinBox(Dialog)
        self.spinBox_baseLine_2.setMaximum(4095)
        self.spinBox_baseLine_2.setObjectName("spinBox_baseLine_2")
        self.horizontalLayout_4.addWidget(self.spinBox_baseLine_2)
        self.horizontalSlider_baseLine_2 = QtWidgets.QSlider(Dialog)
        self.horizontalSlider_baseLine_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.horizontalSlider_baseLine_2.setMaximum(4095)
        self.horizontalSlider_baseLine_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_baseLine_2.setObjectName("horizontalSlider_baseLine_2")
        self.horizontalLayout_4.addWidget(self.horizontalSlider_baseLine_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.label_count_2 = QtWidgets.QLabel(Dialog)
        self.label_count_2.setMinimumSize(QtCore.QSize(30, 0))
        self.label_count_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_count_2.setText("")
        self.label_count_2.setObjectName("label_count_2")
        self.horizontalLayout_2.addWidget(self.label_count_2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.graphicsView = GraphicsView(Dialog)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_5.setText(_translate("Dialog", "层数："))
        self.label_6.setText(_translate("Dialog", "通道："))
        self.label_7.setText(_translate("Dialog", "设置基线"))
        self.label_8.setText(_translate("Dialog", "计数："))
from pyqtgraph import GraphicsView
